/*
PostPuma - OpenAPI 3.0

PostPuma API specifications

API version: 1.0.0
Contact: support@postpuma.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package PostPuma

import (
	"encoding/json"
)

// checks if the DeleteMediaFiles200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteMediaFiles200Response{}

// DeleteMediaFiles200Response struct for DeleteMediaFiles200Response
type DeleteMediaFiles200Response struct {
	Success *bool `json:"success,omitempty"`
}

// NewDeleteMediaFiles200Response instantiates a new DeleteMediaFiles200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteMediaFiles200Response() *DeleteMediaFiles200Response {
	this := DeleteMediaFiles200Response{}
	return &this
}

// NewDeleteMediaFiles200ResponseWithDefaults instantiates a new DeleteMediaFiles200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteMediaFiles200ResponseWithDefaults() *DeleteMediaFiles200Response {
	this := DeleteMediaFiles200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *DeleteMediaFiles200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteMediaFiles200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *DeleteMediaFiles200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *DeleteMediaFiles200Response) SetSuccess(v bool) {
	o.Success = &v
}

func (o DeleteMediaFiles200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteMediaFiles200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	return toSerialize, nil
}

type NullableDeleteMediaFiles200Response struct {
	value *DeleteMediaFiles200Response
	isSet bool
}

func (v NullableDeleteMediaFiles200Response) Get() *DeleteMediaFiles200Response {
	return v.value
}

func (v *NullableDeleteMediaFiles200Response) Set(val *DeleteMediaFiles200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteMediaFiles200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteMediaFiles200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteMediaFiles200Response(val *DeleteMediaFiles200Response) *NullableDeleteMediaFiles200Response {
	return &NullableDeleteMediaFiles200Response{value: val, isSet: true}
}

func (v NullableDeleteMediaFiles200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteMediaFiles200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


