/*
PostPuma - OpenAPI 3.0

PostPuma API specifications

API version: 1.0.0
Contact: support@postpuma.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package PostPuma

import (
	"encoding/json"
)

// checks if the VersionOptionsPinterestBoards type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VersionOptionsPinterestBoards{}

// VersionOptionsPinterestBoards struct for VersionOptionsPinterestBoards
type VersionOptionsPinterestBoards struct {
	Accounts0 *string `json:"accounts-0,omitempty"`
}

// NewVersionOptionsPinterestBoards instantiates a new VersionOptionsPinterestBoards object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVersionOptionsPinterestBoards() *VersionOptionsPinterestBoards {
	this := VersionOptionsPinterestBoards{}
	return &this
}

// NewVersionOptionsPinterestBoardsWithDefaults instantiates a new VersionOptionsPinterestBoards object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVersionOptionsPinterestBoardsWithDefaults() *VersionOptionsPinterestBoards {
	this := VersionOptionsPinterestBoards{}
	return &this
}

// GetAccounts0 returns the Accounts0 field value if set, zero value otherwise.
func (o *VersionOptionsPinterestBoards) GetAccounts0() string {
	if o == nil || IsNil(o.Accounts0) {
		var ret string
		return ret
	}
	return *o.Accounts0
}

// GetAccounts0Ok returns a tuple with the Accounts0 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VersionOptionsPinterestBoards) GetAccounts0Ok() (*string, bool) {
	if o == nil || IsNil(o.Accounts0) {
		return nil, false
	}
	return o.Accounts0, true
}

// HasAccounts0 returns a boolean if a field has been set.
func (o *VersionOptionsPinterestBoards) HasAccounts0() bool {
	if o != nil && !IsNil(o.Accounts0) {
		return true
	}

	return false
}

// SetAccounts0 gets a reference to the given string and assigns it to the Accounts0 field.
func (o *VersionOptionsPinterestBoards) SetAccounts0(v string) {
	o.Accounts0 = &v
}

func (o VersionOptionsPinterestBoards) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VersionOptionsPinterestBoards) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Accounts0) {
		toSerialize["accounts-0"] = o.Accounts0
	}
	return toSerialize, nil
}

type NullableVersionOptionsPinterestBoards struct {
	value *VersionOptionsPinterestBoards
	isSet bool
}

func (v NullableVersionOptionsPinterestBoards) Get() *VersionOptionsPinterestBoards {
	return v.value
}

func (v *NullableVersionOptionsPinterestBoards) Set(val *VersionOptionsPinterestBoards) {
	v.value = val
	v.isSet = true
}

func (v NullableVersionOptionsPinterestBoards) IsSet() bool {
	return v.isSet
}

func (v *NullableVersionOptionsPinterestBoards) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVersionOptionsPinterestBoards(val *VersionOptionsPinterestBoards) *NullableVersionOptionsPinterestBoards {
	return &NullableVersionOptionsPinterestBoards{value: val, isSet: true}
}

func (v NullableVersionOptionsPinterestBoards) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVersionOptionsPinterestBoards) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


