/*
PostPuma - OpenAPI 3.0

PostPuma API specifications

API version: 1.0.0
Contact: support@postpuma.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package PostPuma

import (
	"encoding/json"
)

// checks if the VersionOptionsInstagram type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VersionOptionsInstagram{}

// VersionOptionsInstagram struct for VersionOptionsInstagram
type VersionOptionsInstagram struct {
	Type *string `json:"type,omitempty"`
}

// NewVersionOptionsInstagram instantiates a new VersionOptionsInstagram object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVersionOptionsInstagram() *VersionOptionsInstagram {
	this := VersionOptionsInstagram{}
	return &this
}

// NewVersionOptionsInstagramWithDefaults instantiates a new VersionOptionsInstagram object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVersionOptionsInstagramWithDefaults() *VersionOptionsInstagram {
	this := VersionOptionsInstagram{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *VersionOptionsInstagram) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VersionOptionsInstagram) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *VersionOptionsInstagram) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *VersionOptionsInstagram) SetType(v string) {
	o.Type = &v
}

func (o VersionOptionsInstagram) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VersionOptionsInstagram) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableVersionOptionsInstagram struct {
	value *VersionOptionsInstagram
	isSet bool
}

func (v NullableVersionOptionsInstagram) Get() *VersionOptionsInstagram {
	return v.value
}

func (v *NullableVersionOptionsInstagram) Set(val *VersionOptionsInstagram) {
	v.value = val
	v.isSet = true
}

func (v NullableVersionOptionsInstagram) IsSet() bool {
	return v.isSet
}

func (v *NullableVersionOptionsInstagram) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVersionOptionsInstagram(val *VersionOptionsInstagram) *NullableVersionOptionsInstagram {
	return &NullableVersionOptionsInstagram{value: val, isSet: true}
}

func (v NullableVersionOptionsInstagram) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVersionOptionsInstagram) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


