/*
PostPuma - OpenAPI 3.0

PostPuma API specifications

API version: 1.0.0
Contact: support@postpuma.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package PostPuma

import (
	"encoding/json"
)

// checks if the ListTags200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListTags200Response{}

// ListTags200Response struct for ListTags200Response
type ListTags200Response struct {
	Data interface{} `json:"data,omitempty"`
}

// NewListTags200Response instantiates a new ListTags200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTags200Response() *ListTags200Response {
	this := ListTags200Response{}
	return &this
}

// NewListTags200ResponseWithDefaults instantiates a new ListTags200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTags200ResponseWithDefaults() *ListTags200Response {
	this := ListTags200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListTags200Response) GetData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListTags200Response) GetDataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return &o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListTags200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given interface{} and assigns it to the Data field.
func (o *ListTags200Response) SetData(v interface{}) {
	o.Data = v
}

func (o ListTags200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListTags200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableListTags200Response struct {
	value *ListTags200Response
	isSet bool
}

func (v NullableListTags200Response) Get() *ListTags200Response {
	return v.value
}

func (v *NullableListTags200Response) Set(val *ListTags200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListTags200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListTags200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTags200Response(val *ListTags200Response) *NullableListTags200Response {
	return &NullableListTags200Response{value: val, isSet: true}
}

func (v NullableListTags200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTags200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


